# Generated by Django 4.0.3 on 2022-05-07 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('bio', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
                ('arroba', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
