# Generated by Django 4.0.3 on 2022-05-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='profile_img',
            new_name='profile',
        ),
    ]
